### ISSUE TITLE
Add Container-native load balancing through Ingress and customized LB config

### ISSUE THREAD

**Issue by AuroraLi** [GoogleCloudPlatform/gke-pubsub-websocket-adapter#3]
websocket usually needs some special config on the load balancer including longer timeout and session affinity. 

Suggestion:
1. enable alias IP on GKE
2. use ingress and service backend config:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dyson-ing
spec:
  defaultBackend:
    service:
      name: dyson-taxi-service # Name of the Service targeted by the Ingress
      port:
        number: 80 # Should match the port used by the Service
---
apiVersion: v1
kind: Service
metadata:
  name: dyson-taxi-service # {"$kpt-set":"service-name"}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "websocket"}'
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: dyson-taxi-app # {"$kpt-set":"app-name"}
  type: ClusterIP
---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: websocket
spec:
  sessionAffinity:
    affinityType: "CLIENT_IP"
  timeoutSec: 200
  logging:
    enable: true
```
